# Generated by cpp11: do not edit by hand

add_one_impl <- function(dat, dim) {
  .Call(`_codontest_add_one_impl`, dat, dim)
}

save_npy_impl <- function(file, dat, dim) {
  .Call(`_codontest_save_npy_impl`, file, dat, dim)
}

read_npy_impl <- function(file) {
  .Call(`_codontest_read_npy_impl`, file)
}
