# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Install Codon
        run: |
          mkdir -p $RUNNER_TEMP/.codon
          cd $RUNNER_TEMP/.codon
          export OS=$(uname -s | awk '{print tolower($0)}')
          export ARCH=$(uname -m)
          curl -L https://github.com/exaloop/codon/releases/latest/download/"codon-$OS-$ARCH.tar.gz" | tar zxvf - --strip-components=1
          echo "CODON_DIR=$RUNNER_TEMP/.codon" >> $GITHUB_ENV
          echo "$RUNNER_TEMP/.codon/bin" >> "$GITHUB_PATH"

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
